"""Add role column to team_members table

Revision ID: 7abd2b5638ce
Revises: 875c7d5c74ef
Create Date: 2025-04-30 11:29:45.972902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abd2b5638ce'
down_revision = '875c7d5c74ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_projects')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('leader_id', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['leader_id'], ['id'])
        batch_op.drop_column('max_members')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_members', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('leader_id')
        batch_op.drop_column('updated_at')

    op.create_table('team_projects',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='team_projects_project_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='team_projects_team_id_fkey'),
    sa.PrimaryKeyConstraint('team_id', 'project_id', name='team_projects_pkey')
    )
    # ### end Alembic commands ###
