"""Add activity logs table and rename existing tables

Revision ID: 93e2f1c8fd67
Revises: 778d75e4ca89
Create Date: 2025-04-30 15:31:52.083398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93e2f1c8fd67'
down_revision = '778d75e4ca89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First rename existing tables
    op.rename_table('user', 'users')
    op.rename_table('team', 'teams')
    op.rename_table('project', 'projects')
    op.rename_table('ticket', 'tickets')
    op.rename_table('comment', 'comments')
    
    # Create activity_logs table
    op.create_table('activity_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('activity_type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=False),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('resource_type', sa.String(length=50), nullable=True),
        sa.Column('resource_id', sa.Integer(), nullable=True),
        sa.Column('additional_data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Update foreign key constraints
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('team_members_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('team_members_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('ticket_assignee_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('ticket_creator_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('ticket_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assignee_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
    
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comment_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comment_ticket_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'])
    
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('project_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('team_leader_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['leader_id'], ['id'], ondelete='SET NULL')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop activity_logs table
    op.drop_table('activity_logs')
    
    # Restore foreign key constraints
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('team_leader_id_fkey', 'user', ['leader_id'], ['id'], ondelete='SET NULL')
    
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_team_id_fkey', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ticket_id_fkey', 'ticket', ['ticket_id'], ['id'])
        batch_op.create_foreign_key('comment_author_id_fkey', 'user', ['author_id'], ['id'])
    
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ticket_project_id_fkey', 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key('ticket_creator_id_fkey', 'user', ['creator_id'], ['id'])
        batch_op.create_foreign_key('ticket_assignee_id_fkey', 'user', ['assignee_id'], ['id'])
    
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('team_members_team_id_fkey', 'team', ['team_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('team_members_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Rename tables back
    op.rename_table('comments', 'comment')
    op.rename_table('tickets', 'ticket')
    op.rename_table('projects', 'project')
    op.rename_table('teams', 'team')
    op.rename_table('users', 'user')
    
    # ### end Alembic commands ###
