"""Add password reset token fields to User model

Revision ID: a5e102938bfc
Revises: 7abd2b5638ce
Create Date: 2025-04-30 12:19:01.790166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e102938bfc'
down_revision = '7abd2b5638ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('team_leader_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['leader_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint('team_members_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('team_members_team_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['team_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('team_members_team_id_fkey', 'team', ['team_id'], ['id'])
        batch_op.create_foreign_key('team_members_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('team_leader_id_fkey', 'user', ['leader_id'], ['id'])

    # ### end Alembic commands ###
